### ISSUE TITLE
Open attachments is not working

### ISSUE THREAD

**Issue by JocelynDelalande** [flathub/org.gnome.Geary#15] opened 2019-03-01 09:06 UTC
I can not open attachments using flatpak-installed geary. Saving them works.

When i double-click on attachment just nothing happens

I suspect it comes from flatpak package and not from geary itself but unsure. 

Here is what I have in console when trying to open an attachment (double-click on attachment) :

```
*[wrn] 09:09:20 43,912799 GLib-GObject: g_object_notify: object class 'GNetworkMonitorPortal' has no property named 'available'
(process:21): GLib-GObject-WARNING **: 09:09:20.701: g_object_notify: object class 
'GNetworkMonitorPortal' has no property named 'available'
```

Context:
- Debian stable (stretch), up-to-date
- Geary versions tested :
  - org.gnome.Geary/x86_64/master    gnome-apps-nightly 7a4829bdc53c - 7,2 MB          
  - org.gnome.Geary/x86_64/stable    flathub            74b391bc3d52 - 7,4 MB  current

**Comment by Pshemas** [comment] 2019-04-01 18:13
same on my end. (btw - how did you get console output while using flatpak?)

**Comment by mjog** [comment] 2019-04-02 05:13
@Pshemas you can run Geary from a terminal using `flatpak run org.gnome.Geary`, and if you add a ` -d` to the end of it you'll get a lot of debug info out of it.

**Comment by mjog** [comment] 2019-04-02 05:17
NB, this probably isn't a bug in Geary, we just use the standard toolkit API calls to do things like open files, etc.

If this isn't working for you, there might be some Flatpak integration problem, or perhaps your session DBus is having some so Geary can't talk to the required Flatpak portals.

Try restarting Geary, and if that doesn't help, log out of your desktop session and log back in again. If either fixes it, then it was likely a DBus-related problem. If not, it's probably a Flatpak/portal problem.

Can you both try the above and let me know if helps?

**Comment by mjog** [comment] 2019-07-16 22:51
@JocelynDelalande, if this is still a problem for you, can you please try running Geary from a terminal using this command:

```
flatpak run org.gnome.Geary -d | tee geary.txt
```

Wait for Geary to start up and the debug messages to stop printing in the terminal, then attempt to open an attachment. When that fails, quit the app, open `geary.txt` in a text editor and redact any private information, then attach it here? That should say what the issue is so I can better diagnose it.

**Comment by mjog** [comment] 2019-08-12 05:31
Closing since the requested information was not provided. Please reopen if you can still reproduce the problem and get those logs. Thanks!

**Closed by mjog** 2019-08-12 05:31 UTC
Labels: flatpak, need information
