### ISSUE TITLE
Attachments don't open correctly

### ISSUE THREAD

**Issue by Pshemas** [flathub/org.gnome.Geary#25] opened 2019-08-18 11:43 UTC
While I love Geary the flatpak version is quite bugged, especially when it comes to attachments.

First of all - when I double click an attachment it does not open. Saving it, then opening in external app works, but having an option to quickly view files is super handy.
And when it comes to saving there's another issue. When you mark a single attachment and click save it works - for example on KDE I get native Plasma's file dialog and can choose where to save etc. 
But when you try to save multiple files it fails. I'm getting non-native file dialog (so on KDE I get GTKs file dialog, instead of Plasma's) and it doesn't have proper permissions that would allow me to save attachments somewhere in my home folder.

**Comment by mjog** [comment] 2019-08-30 10:53
Hi, thanks for the bug report. Geary simply uses the standard platform APIs for opening and saving attachments, so if these aren't working then the problem is 99% likely to be an issue with the Flatpak portals (i.e. xdg-desktop-portal and xdg-desktop-portal-kde), the platform APIs in use (i.e. GLib and GTK), or you system's configuration.

The problem with saving multiple attachments is a known issue, and requires portal and GTK work to get fixed: https://github.com/flatpak/xdg-desktop-portal/issues/158

I'm not sure what the problem is with opening attachments - it works under GNOME for me. So maybe a bug in xdg-desktop-portal and xdg-desktop-portal-kde?). If you'd like to post some debugging information I'll take a look and see if anything in particular stand out. Run Geary from a terminal using the following command:

```
flatpak run org.gnome.Geary -d | tee geary.txt
```

Try opening an attachment, and when it fails, quit the app. Edit the `geary.txt` file to redact any private information, and attach it here.

**Comment by mjog** [comment] 2019-10-24 04:03
Closing since the requested information has not been provided. Please reopen logs can be provided.

**Closed by mjog** 2019-10-24 04:03 UTC
Labels: flatpak, need information

**Comment by Pshemas** [comment] 2019-11-04 09:05
Of course I'll test under Gnome as well - but if I recall correctly I had identical problem there. Click open attachment, get a warning, confirm you wish to open.... and nothing happens. 
I've prepared the file as requested. Is there anything I should remove (apart from email address) / other sensitive parts I should be aware of?
