### ISSUE TITLE
GDBus.Error:org.gnome.OnlineAccounts.Error.NotAuthorized

### ISSUE THREAD

**Issue by FlorianLudwig** [flathub/org.gnome.Geary#11] opened 2019-02-20 17:49 UTC
directly when starting geary I receive the error a notification "geary has encountered a problem" and the details say:

GDBus.Error:org.gnome.OnlineAccounts.Error.NotAuthorized: Failed to retrieve credentials from the keyring

I suspect this is related to sandboxing by flatpack so I report this here.  I don't have this verion of geary available on my system without flatpack.

Version: 0.13
System: Fedora 29

**Comment by mjog** [comment] 2019-02-21 02:22
Hey, thanks for the bug report. I can't reproduce this locally on my Ubuntu system, and haven't heard of similar reports from others. Occasionally Flatpak and the DBus session bus can get messed up though - is it still a problem if you log out and log back in again?

**Comment by SufianBabri** [comment] 2019-06-13 11:53
In my case, the Gnome's Online Account had an issue, basically [this bug](https://bugs.launchpad.net/ubuntu/+source/gnome-online-accounts/+bug/1610944).

The solution so far is to run following command every time I log in to my system profile/account.

```
$ pkill -f goa
```

**Comment by JpegXguy** [comment] 2019-07-03 10:47
I have this as well. Thanks for the workaround. IT specifically happens if I log out and back in. Seems like it's that bug indeed

**Comment by mjog** [comment] 2019-07-16 22:41
Thanks for the feedback, everyone. Closing, since this isn't a bug in Geary.

**Closed by mjog** 2019-07-16 22:41 UTC
Labels: need information

**Comment by igorgue** [comment] 2025-04-28 04:24
@SufianBabri thanks for the workaround, it happens when you login and out currently (6 years after this report, it still happens).
